<a href="https://colab.research.google.com/github/angel-myr/prep-python/blob/main/numpy_ez.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

---
# Numpy Parte III
---

In [245]:
import numpy as np
import pandas as pd
import time

ruta_sales = 'supermarket_sales.xlsx'
df_sales = pd.read_excel(ruta_sales)

df_sales

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,2019-01-05,13:08:00,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,2019-03-08,10:29:00,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,2019-03-03,13:23:00,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,2019-01-27,20:33:00,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2019-02-08,10:37:00,Ewallet,604.17,4.761905,30.2085,5.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,233-67-5758,C,Naypyitaw,Normal,Male,Health and beauty,40.35,1,2.0175,42.3675,2019-01-29,13:46:00,Ewallet,40.35,4.761905,2.0175,6.2
996,303-96-2227,B,Mandalay,Normal,Female,Home and lifestyle,97.38,10,48.6900,1022.4900,2019-03-02,17:16:00,Ewallet,973.80,4.761905,48.6900,4.4
997,727-02-1313,A,Yangon,Member,Male,Food and beverages,31.84,1,1.5920,33.4320,2019-02-09,13:22:00,Cash,31.84,4.761905,1.5920,7.7
998,347-56-2442,A,Yangon,Normal,Male,Home and lifestyle,65.82,1,3.2910,69.1110,2019-02-22,15:33:00,Cash,65.82,4.761905,3.2910,4.1


In [246]:
df_sales['Quantity'].mean()

np.float64(5.51)

In [247]:
np.round(df_sales['Quantity'].mean())

np.float64(6.0)

In [248]:
np.round(np.min(df_sales['Total'])), np.round(np.max(df_sales['Total']))

(np.float64(11.0), np.float64(1043.0))

## Arrays en Numpy

In [249]:
ingreso_bruto = np.array(df_sales['gross income'])
ingreso_bruto

array([26.1415,  3.82  , 16.2155, 23.288 , 30.2085, 29.8865, 20.652 ,
       36.78  ,  3.626 ,  8.226 ,  2.896 ,  5.102 , 11.7375, 21.595 ,
       35.69  , 28.116 , 24.1255, 21.783 ,  8.2005,  4.03  , 21.51  ,
       13.197 ,  3.32  ,  8.64  , 13.2945, 21.036 ,  1.676 ,  8.767 ,
       22.09  , 11.2005, 23.5325, 35.1315, 33.512 ,  9.658 , 19.884 ,
        3.406 , 15.655 , 27.396 , 21.968 , 12.048 ,  4.336 ,  5.611 ,
       20.736 , 39.48  ,  1.537 , 18.792 , 25.5105,  9.0045,  5.679 ,
       41.315 , 31.99  , 11.1475,  3.574 ,  0.7715,  1.616 , 34.392 ,
        4.434 , 35.84  , 36.175 ,  9.183 ,  3.711 , 16.719 , 24.7815,
        7.905 , 15.148 ,  7.935 ,  3.347 , 29.283 , 39.385 ,  0.9165,
       44.74  , 31.06  ,  7.278 , 22.773 , 33.6015, 20.825 , 22.068 ,
        9.0045, 39.155 ,  5.095 , 29.757 , 14.502 ,  7.7   , 16.072 ,
       12.2275, 29.071 , 19.13  , 17.283 ,  2.1235, 23.097 ,  9.476 ,
       22.43  ,  7.693 , 28.962 ,  4.4875,  4.858 , 43.935 ,  3.735 ,
        7.9125, 24.8

In [250]:
init_recorrido = time.time()
ingreso_bruto ** 2
end_recorrido = time.time()
print(f'Tiempo de recorrido: {end_recorrido - init_recorrido}')

Tiempo de recorrido: 0.0005998611450195312


## Tipos de Arrays

In [251]:
len(ingreso_bruto)

1000

In [252]:
ingreso_bruto.shape

(1000,)

In [253]:
# Array bidimensional
ingreso_rebruto = np.column_stack((ingreso_bruto, ingreso_bruto ** 2))
ingreso_rebruto

array([[ 26.1415, 683.378 ],
       [  3.82  ,  14.5924],
       [ 16.2155, 262.9424],
       ...,
       [  1.592 ,   2.5345],
       [  3.291 ,  10.8307],
       [ 30.919 , 955.9846]])

In [254]:
len(ingreso_rebruto)

1000

In [255]:
ingreso_rebruto.shape

(1000, 2)

## Manipulación de Arrays

In [256]:
# Concatenación
precio_unitario = np.array(df_sales['Unit price'])
cantidad = np.array(df_sales['Quantity'])
impuesto = np.array(df_sales['Tax 5%'])
total = np.array(df_sales['Total'])

np.concatenate([precio_unitario, cantidad, impuesto])

array([74.69 , 15.28 , 46.33 , ...,  1.592,  3.291, 30.919])

In [257]:
np.concatenate([precio_unitario, cantidad, impuesto], axis = 0)

array([74.69 , 15.28 , 46.33 , ...,  1.592,  3.291, 30.919])

In [258]:
# Alterar tamaño
valor_concatenado = np.concatenate([precio_unitario, cantidad, impuesto], axis = 0)
valor_concatenado.shape

(3000,)

In [259]:
valor_reformado = valor_concatenado.reshape(1000, 3)
valor_reformado

array([[74.69  , 15.28  , 46.33  ],
       [58.22  , 86.31  , 85.39  ],
       [68.84  , 73.56  , 36.26  ],
       ...,
       [38.3   ,  5.803 ,  8.745 ],
       [ 3.0475,  2.0175, 48.69  ],
       [ 1.592 ,  3.291 , 30.919 ]])

In [260]:
valor_reformado = valor_concatenado.reshape(3, 1000)
valor_reformado

array([[74.69  , 15.28  , 46.33  , ..., 31.84  , 65.82  , 88.34  ],
       [ 7.    ,  5.    ,  7.    , ...,  1.    ,  1.    ,  7.    ],
       [26.1415,  3.82  , 16.2155, ...,  1.592 ,  3.291 , 30.919 ]])

In [261]:
# Trasponer
valor_reformado = valor_reformado.T
valor_reformado

array([[74.69  ,  7.    , 26.1415],
       [15.28  ,  5.    ,  3.82  ],
       [46.33  ,  7.    , 16.2155],
       ...,
       [31.84  ,  1.    ,  1.592 ],
       [65.82  ,  1.    ,  3.291 ],
       [88.34  ,  7.    , 30.919 ]])

In [262]:
# Operaciones
ganancia_bruta = precio_unitario * cantidad
ganancia_bruta

array([522.83,  76.4 , 324.31, 465.76, 604.17, 597.73, 413.04, 735.6 ,
        72.52, 164.52,  57.92, 102.04, 234.75, 431.9 , 713.8 , 562.32,
       482.51, 435.66, 164.01,  80.6 , 430.2 , 263.94,  66.4 , 172.8 ,
       265.89, 420.72,  33.52, 175.34, 441.8 , 224.01, 470.65, 702.63,
       670.24, 193.16, 397.68,  68.12, 313.1 , 547.92, 439.36, 240.96,
        86.72, 112.22, 414.72, 789.6 ,  30.74, 375.84, 510.21, 180.09,
       113.58, 826.3 , 639.8 , 222.95,  71.48,  15.43,  32.32, 687.84,
        88.68, 716.8 , 723.5 , 183.66,  74.22, 334.38, 495.63, 158.1 ,
       302.96, 158.7 ,  66.94, 585.66, 787.7 ,  18.33, 894.8 , 621.2 ,
       145.56, 455.46, 672.03, 416.5 , 441.36, 180.09, 783.1 , 101.9 ,
       595.14, 290.04, 154.  , 321.44, 244.55, 581.42, 382.6 , 345.66,
        42.47, 461.94, 189.52, 448.6 , 153.86, 579.24,  89.75,  97.16,
       878.7 ,  74.7 , 158.25, 496.2 ,  48.71, 706.95, 207.63, 349.56,
       212.45, 886.7 , 164.28, 372.78, 305.82, 819.7 ,  32.98, 294.63,
      

## Indexación y Segmentación de Arrays

In [263]:
rating = np.array(df_sales['Rating'])
rating[500:505]

array([5.4, 9.1, 9. , 6.3, 9.5])

In [264]:
# Hasta el unidimensinal 2, y hasta el elemento 3
valor_reformado[:2, :3]

array([[74.69  ,  7.    , 26.1415],
       [15.28  ,  5.    ,  3.82  ]])

In [265]:
# Información
(rating[250:750] > 5.99)

array([ True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True, False, False, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False, False,  True,  True, False,  True, False,
        True,  True, False, False,  True,  True, False, False, False,
        True, False,  True, False, False,  True, False,  True, False,
       False, False, False,  True, False,  True,  True, False,  True,
        True,  True,  True,  True, False,  True, False,  True,  True,
        True, False,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False, False,
       False,  True, False,  True, False,  True,  True,  True, False,
        True, False,  True,  True,  True,  True,  True,  True, False,
        True, False,  True,  True, False, False,  True,  True,  True,
        True,  True,

## Forma y Estructura de Arrays

In [266]:
valor_reformado

array([[74.69  ,  7.    , 26.1415],
       [15.28  ,  5.    ,  3.82  ],
       [46.33  ,  7.    , 16.2155],
       ...,
       [31.84  ,  1.    ,  1.592 ],
       [65.82  ,  1.    ,  3.291 ],
       [88.34  ,  7.    , 30.919 ]])

In [267]:
valor_reformado.transpose()

array([[74.69  , 15.28  , 46.33  , ..., 31.84  , 65.82  , 88.34  ],
       [ 7.    ,  5.    ,  7.    , ...,  1.    ,  1.    ,  7.    ],
       [26.1415,  3.82  , 16.2155, ...,  1.592 ,  3.291 , 30.919 ]])

In [268]:
valor_reformado.transpose().flatten()

array([74.69 , 15.28 , 46.33 , ...,  1.592,  3.291, 30.919])

## Operaciones avanzadas y Funciones Universales

In [269]:
np.multiply(precio_unitario, cantidad)

array([522.83,  76.4 , 324.31, 465.76, 604.17, 597.73, 413.04, 735.6 ,
        72.52, 164.52,  57.92, 102.04, 234.75, 431.9 , 713.8 , 562.32,
       482.51, 435.66, 164.01,  80.6 , 430.2 , 263.94,  66.4 , 172.8 ,
       265.89, 420.72,  33.52, 175.34, 441.8 , 224.01, 470.65, 702.63,
       670.24, 193.16, 397.68,  68.12, 313.1 , 547.92, 439.36, 240.96,
        86.72, 112.22, 414.72, 789.6 ,  30.74, 375.84, 510.21, 180.09,
       113.58, 826.3 , 639.8 , 222.95,  71.48,  15.43,  32.32, 687.84,
        88.68, 716.8 , 723.5 , 183.66,  74.22, 334.38, 495.63, 158.1 ,
       302.96, 158.7 ,  66.94, 585.66, 787.7 ,  18.33, 894.8 , 621.2 ,
       145.56, 455.46, 672.03, 416.5 , 441.36, 180.09, 783.1 , 101.9 ,
       595.14, 290.04, 154.  , 321.44, 244.55, 581.42, 382.6 , 345.66,
        42.47, 461.94, 189.52, 448.6 , 153.86, 579.24,  89.75,  97.16,
       878.7 ,  74.7 , 158.25, 496.2 ,  48.71, 706.95, 207.63, 349.56,
       212.45, 886.7 , 164.28, 372.78, 305.82, 819.7 ,  32.98, 294.63,
      

In [270]:
np.add(cantidad, rating)

array([16.1, 14.6, 14.4, 16.4, 12.3, 11.1, 11.8, 18. ,  9.2,  8.9,  8.5,
       10.8, 12.1, 18.2, 15.7, 10.5, 11.6, 12.9, 11.6,  6.4,  9.8,  8.1,
        6.4, 14.9,  9. , 16.5,  7.7,  9.7, 14.6, 16.4,  9.8, 13.5, 13.1,
        7.1, 11.5,  7.8, 12. , 13.7, 15.6, 15.7,  8.9,  8.3, 11.6, 15.6,
        9.2, 13.5, 17.4, 13.1, 14.1, 17.9, 16.5, 13.5, 10.5,  7.1,  8.5,
       16.2,  7.8, 14.6, 15.4, 15.3, 13. , 13. , 19. , 18.6, 11.6, 15.8,
        8.7, 15.9, 16.4,  5.3, 19.6, 15.9,  7. , 14.7, 18.4, 15.4, 17.6,
       14.7, 16.6, 11. , 11.5,  9.4, 14.6, 12.3, 11.6, 11. , 14.9, 14.3,
        6.7, 12.1, 11.1, 18.2, 12.1, 17.6,  7.6,  8.2, 15.1, 10.1, 12.3,
       13.4,  5.1, 16.2, 13.9, 15.9, 15. , 17.3, 13.9, 13.4, 13.2, 19.2,
        6.6, 10.8, 15.4, 13.3, 18.5, 10.1, 10.3,  6.2, 16. ,  6.1, 13.2,
       13.5, 13.2, 12.6, 15.3, 11.5, 14. , 14.9, 16.5, 16.2, 14.5, 14.3,
       11.4, 14.8, 11.3,  9.2, 13.8, 15.8, 18.2, 17.2, 15.4, 18.1, 19.1,
        9.4, 14. , 15.5, 19.2,  9.6, 14.2, 12.9,  8

In [271]:
np.subtract(
    total,
    np.add(
        np.multiply(precio_unitario, cantidad),
        impuesto
    )
)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -0.,  0.,
        0.,  0.,  0., -0.,  0.,  0.,  0., -0.,  0.,  0.,  0.,  0., -0.,
       -0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -0.,  0.,  0., -0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -0., -0.,
        0.,  0.,  0., -0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0., -0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0., -0.,  0.,  0.,  0., -0.,  0., -0.,  0.,  0.,  0.,
       -0., -0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
       -0., -0.,  0., -0.,  0., -0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0., -0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -0.,  0.,
        0.,  0.,  0., -0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0., -0.,  0.,  0.,  0.,  0.,  0.,  0., -0.,  0.,  0.,  0., -0.,
       -0.,  0.,  0., -0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0., -0., -0.,  0., -0.,  0., -0.,  0.,  0., -0

In [272]:
np.log(total)

array([6.308 , 4.3848, 5.8305, 6.1925, 6.4526, 6.4419, 6.0723, 6.6495,
       4.3327, 5.1518, 4.1079, 4.6742, 5.5073, 6.117 , 6.6194, 6.3809,
       6.2278, 6.1257, 5.1487, 4.4383, 6.113 , 5.6245, 4.2445, 5.2009,
       5.6319, 6.0908, 3.5609, 5.2155, 6.1396, 5.4605, 6.2029, 6.6036,
       6.5564, 5.3123, 6.0344, 4.2701, 5.7953, 6.3549, 6.1341, 5.5334,
       4.5115, 4.7693, 6.0764, 6.7203, 3.4744, 5.978 , 6.2836, 5.2422,
       4.7813, 6.7657, 6.5099, 5.4557, 4.3182, 2.7851, 3.5245, 6.5823,
       4.5338, 6.6236, 6.6329, 5.2619, 4.3558, 5.8611, 6.2546, 5.112 ,
       5.7624, 5.1158, 4.2526, 6.4215, 6.7179, 2.9573, 6.8454, 6.4804,
       5.0294, 6.1701, 6.5591, 6.0807, 6.1387, 5.2422, 6.7121, 4.6728,
       6.4376, 5.7188, 5.0857, 5.8216, 5.5482, 6.4143, 5.9958, 5.8942,
       3.7976, 6.1842, 5.2933, 6.1549, 5.0848, 6.4105, 4.5458, 4.6251,
       6.8272, 4.3623, 5.113 , 6.2558, 3.9347, 6.6098, 5.3845, 5.9055,
       5.4075, 6.8363, 5.1504, 5.9698, 5.7718, 6.7577, 3.5447, 5.7345,
      

In [273]:
np.exp(total)

/tmp/ipykernel_1986/190601779.py:1: RuntimeWarning: overflow encountered in exp
  np.exp(total)


array([2.6019e+238, 6.9040e+034, 7.7330e+147, 2.4595e+212, 3.2143e+275,
       3.7186e+272, 2.2389e+188,         inf, 1.1743e+033, 1.0535e+075,
       2.5826e+026, 3.3977e+046, 1.1173e+107, 8.9202e+196,         inf,
       2.6491e+256, 1.0691e+220, 4.6235e+198, 6.1669e+074, 5.6799e+036,
       1.4968e+196, 2.2860e+120, 1.9011e+030, 6.2862e+078, 1.7713e+121,
       7.1153e+191, 1.9294e+015, 9.0501e+079, 2.9165e+201, 1.4146e+102,
       4.1757e+214,         inf, 4.3213e+305, 1.2099e+088, 2.2169e+181,
       1.1570e+031, 5.9770e+142, 7.1873e+249, 2.2501e+200, 7.5854e+109,
       3.5085e+039, 1.4906e+051, 1.3066e+189,         inf, 1.0417e+014,
       2.4350e+171, 4.5757e+232, 1.3265e+082, 6.2162e+051,         inf,
       5.6845e+291, 4.6479e+101, 3.9404e+032, 1.0870e+007, 5.4729e+014,
               inf, 2.7472e+040,         inf,         inf, 5.6318e+083,
       6.9985e+033, 3.0224e+152, 1.0276e+226, 1.2447e+072, 1.4209e+138,
       2.3370e+072, 3.3516e+030, 1.1651e+267,         inf, 2.283

In [274]:
np.log10(total)

array([2.7395, 1.9043, 2.5321, 2.6894, 2.8023, 2.7977, 2.6372, 2.8878,
       1.8816, 2.2374, 1.784 , 2.03  , 2.3918, 2.6566, 2.8748, 2.7712,
       2.7047, 2.6603, 2.2361, 1.9275, 2.6549, 2.4427, 1.8434, 2.2587,
       2.4459, 2.6452, 1.5465, 2.2651, 2.6664, 2.3715, 2.6939, 2.8679,
       2.8474, 2.3071, 2.6207, 1.8545, 2.5169, 2.7599, 2.664 , 2.4031,
       1.9593, 2.0713, 2.6389, 2.9186, 1.5089, 2.5962, 2.7289, 2.2767,
       2.0765, 2.9383, 2.8272, 2.3694, 1.8754, 1.2096, 1.5307, 2.8587,
       1.969 , 2.8766, 2.8806, 2.2852, 1.8917, 2.5454, 2.7163, 2.2201,
       2.5026, 2.2218, 1.8469, 2.7888, 2.9176, 1.2844, 2.9729, 2.8144,
       2.1842, 2.6796, 2.8486, 2.6408, 2.666 , 2.2767, 2.915 , 2.0294,
       2.7958, 2.4836, 2.2087, 2.5283, 2.4096, 2.7857, 2.6039, 2.5598,
       1.6493, 2.6858, 2.2988, 2.673 , 2.2083, 2.784 , 1.9742, 2.0087,
       2.965 , 1.8945, 2.2205, 2.7168, 1.7088, 2.8706, 2.3385, 2.5647,
       2.3484, 2.969 , 2.2368, 2.5926, 2.5067, 2.9348, 1.5394, 2.4905,
      

In [275]:
np.sqrt(total)

array([23.4301,  8.9566, 18.4533, 22.1144, 25.1869, 25.0523, 20.8253,
       27.7917,  8.7262, 13.1433,  7.7985, 10.3509, 15.6999, 21.2954,
       27.3768, 24.2989, 22.5086, 21.3879, 13.1229,  9.1995, 21.2535,
       16.6474,  8.3499, 13.47  , 16.7088, 21.018 ,  5.9326, 13.5686,
       21.5381, 15.3366, 22.2302, 27.1618, 26.5283, 14.2414, 20.4344,
        8.4573, 18.1316, 23.9857, 21.4785, 15.9062,  9.5423, 10.855 ,
       20.8676, 28.7937,  5.6813, 19.8653, 23.1456, 13.7512, 10.9206,
       29.4553, 25.9189, 15.3002,  8.6634,  4.0251,  5.8255, 26.8744,
        9.6496, 27.4343, 27.5622, 13.8868,  8.8279, 18.7376, 22.8125,
       12.8843, 17.8356, 12.9087,  8.3837, 24.798 , 28.7591,  4.3871,
       30.6519, 25.5394, 12.3628, 21.8685, 26.5637, 20.9123, 21.5274,
       13.7512, 28.675 , 10.3438, 24.9979, 17.4511, 12.7161, 18.3715,
       16.0243, 24.7081, 20.0432, 19.0511,  6.6778, 22.0236, 14.1066,
       21.7032, 12.7104, 24.6618,  9.7076, 10.1004, 30.3749,  8.8564,
       12.8904, 22.8

## Datos faltantes

In [276]:
bancarios = np.array([1.85, 2.13, np.nan, 4.25, 5.08])
bancarios

array([1.85, 2.13,  nan, 4.25, 5.08])

In [277]:
np.isnan(bancarios)

array([False, False,  True, False, False])

In [278]:
np.mean(bancarios)

np.float64(nan)

In [279]:
# Funciones para arreglos con vacíos
np.nanmean(bancarios)

np.float64(3.3275)

In [280]:
# Sustituir por valores válidos
bancarios_validos = np.where(
    np.isnan(bancarios),
    np.nanmean(bancarios),
    bancarios
)

bancarios_validos

array([1.85  , 2.13  , 3.3275, 4.25  , 5.08  ])

In [281]:
# Eliminar elementos no válidos
bancarios_validos = bancarios[~np.isnan(bancarios)]
bancarios_validos

array([1.85, 2.13, 4.25, 5.08])

## Exportación e Importación de Datos

In [282]:
pagos = np.genfromtxt('Pagos.csv', delimiter=',')
pagos

array([[        nan,         nan,         nan, ...,         nan,
                nan,         nan],
       [        nan, 42682691.  ,      331.  , ...,        0.  ,
             229.98,        0.  ],
       [        nan, 40119499.  ,      305.  , ...,        0.  ,
             199.99,        0.  ],
       ...,
       [        nan, 43189845.  ,       69.  , ...,        0.  ,
             252.64,        0.  ],
       [        nan, 20100839.  ,       79.  , ...,        0.  ,
             301.97,        0.  ],
       [        nan, 40010570.  ,       62.  , ...,        0.  ,
             499.92,        0.  ]])

In [283]:
pagos = np.genfromtxt(
    'Pagos.csv',
    delimiter=',',
    filling_values=0,
    skip_header=1,
    dtype = int
)
pagos

array([[       0, 42682691,      331, ...,        0,        0,        0],
       [       0, 40119499,      305, ...,        0,        0,        0],
       [       0, 42317124,      375, ...,        0,        0,        0],
       ...,
       [       0, 43189845,       69, ...,        0,        0,        0],
       [       0, 20100839,       79, ...,        0,        0,        0],
       [       0, 40010570,       62, ...,        0,        0,        0]])

In [284]:
# Eliminar columnas con puros ceros
pagos_numericos = pagos[:, ~np.all(pagos == 0, axis=0)]
pagos_numericos

array([[   42682691,         331,        6735,           1, 90935236916],
       [   40119499,         305,       11427,           1, 90968113434],
       [   42317124,         375,        8774,           1, 90911269609],
       ...,
       [   43189845,          69,        3760,           2, 90944298234],
       [   20100839,          79,        3131,           1, 90995457601],
       [   40010570,          62,         594,           1, 90960219630]])

In [285]:
# Exportar
np.savetxt(
    'pagos_numericos.csv',
    pagos_numericos,
    delimiter=';',
    fmt='%d'
)

## Numpy + Pandas

In [286]:
df_nano = df_sales[['Unit price', 'Quantity', 'Tax 5%', 'Total', 'cogs', 'gross margin percentage', 'gross income', 'Rating']].head(5)

df_nano

,Unit price,Quantity,Tax 5%,Total,cogs,gross margin percentage,gross income,Rating
0,74.69,7,26.1415,548.9715,522.83,4.761905,26.1415,9.1
1,15.28,5,3.8200,80.2200,76.40,4.761905,3.8200,9.6
2,46.33,7,16.2155,340.5255,324.31,4.761905,16.2155,7.4
3,58.22,8,23.2880,489.0480,465.76,4.761905,23.2880,8.4
4,86.31,7,30.2085,634.3785,604.17,4.761905,30.2085,5.3


In [287]:
# De Dataframe a Array
sales_primary = df_nano[['Unit price', 'Quantity', 'Tax 5%', 'Total']].values
sales_primary

array([[ 74.69  ,   7.    ,  26.1415, 548.9715],
       [ 15.28  ,   5.    ,   3.82  ,  80.22  ],
       [ 46.33  ,   7.    ,  16.2155, 340.5255],
       [ 58.22  ,   8.    ,  23.288 , 489.048 ],
       [ 86.31  ,   7.    ,  30.2085, 634.3785]])

In [288]:
sales_secondary = df_nano[['cogs', 'gross margin percentage', 'gross income', 'Rating']].to_numpy()
sales_secondary

array([[522.83  ,   4.7619,  26.1415,   9.1   ],
       [ 76.4   ,   4.7619,   3.82  ,   9.6   ],
       [324.31  ,   4.7619,  16.2155,   7.4   ],
       [465.76  ,   4.7619,  23.288 ,   8.4   ],
       [604.17  ,   4.7619,  30.2085,   5.3   ]])

In [289]:
# Comparten funciones
np.sqrt(df_sales['cogs'].head(3))

,cogs
0,22.865476
1,8.740709
2,18.008609


In [290]:
np.max(df_sales['gross income'].head(3))

26.1415

In [291]:
# De Array a Dataframe
df_filtrado = pd.DataFrame(sales_primary, columns=['precio_unitario', 'cantidad', 'impuesto', 'total'])
df_filtrado

,precio_unitario,cantidad,impuesto,total
0,74.69,7.0,26.1415,548.9715
1,15.28,5.0,3.8200,80.2200
2,46.33,7.0,16.2155,340.5255
3,58.22,8.0,23.2880,489.0480
4,86.31,7.0,30.2085,634.3785


## Proyecto

In [292]:
sales_primary = sales_primary.T
sales_primary

array([[ 74.69  ,  15.28  ,  46.33  ,  58.22  ,  86.31  ],
       [  7.    ,   5.    ,   7.    ,   8.    ,   7.    ],
       [ 26.1415,   3.82  ,  16.2155,  23.288 ,  30.2085],
       [548.9715,  80.22  , 340.5255, 489.048 , 634.3785]])

In [293]:
sales_primary = np.vstack((sales_primary, sales_primary[0] * sales_primary[1]))
sales_primary

array([[ 74.69  ,  15.28  ,  46.33  ,  58.22  ,  86.31  ],
       [  7.    ,   5.    ,   7.    ,   8.    ,   7.    ],
       [ 26.1415,   3.82  ,  16.2155,  23.288 ,  30.2085],
       [548.9715,  80.22  , 340.5255, 489.048 , 634.3785],
       [522.83  ,  76.4   , 324.31  , 465.76  , 604.17  ]])

In [294]:
sales_primary = np.vstack((sales_primary, sales_primary[4] * 0.05))
sales_primary

array([[ 74.69  ,  15.28  ,  46.33  ,  58.22  ,  86.31  ],
       [  7.    ,   5.    ,   7.    ,   8.    ,   7.    ],
       [ 26.1415,   3.82  ,  16.2155,  23.288 ,  30.2085],
       [548.9715,  80.22  , 340.5255, 489.048 , 634.3785],
       [522.83  ,  76.4   , 324.31  , 465.76  , 604.17  ],
       [ 26.1415,   3.82  ,  16.2155,  23.288 ,  30.2085]])

In [295]:
sales_primary = np.vstack((sales_primary, sales_primary[4] + sales_primary[5]))
sales_primary

array([[ 74.69  ,  15.28  ,  46.33  ,  58.22  ,  86.31  ],
       [  7.    ,   5.    ,   7.    ,   8.    ,   7.    ],
       [ 26.1415,   3.82  ,  16.2155,  23.288 ,  30.2085],
       [548.9715,  80.22  , 340.5255, 489.048 , 634.3785],
       [522.83  ,  76.4   , 324.31  , 465.76  , 604.17  ],
       [ 26.1415,   3.82  ,  16.2155,  23.288 ,  30.2085],
       [548.9715,  80.22  , 340.5255, 489.048 , 634.3785]])